-- Reference data taken from the supplied six-page form. Marks are configuration, not code.

-- Codes and groupings are those printed on the official form (CE, ME, ECE/ECT, EEE, CSE/IT, AIML/CAI/DS, BSH, MBA);
-- names follow the programme names on srivasaviengg.ac.in.
INSERT INTO departments (code, name) VALUES
 ('CE','Civil Engineering'),
 ('ME','Mechanical Engineering'),
 ('ECE','Electronics & Communication Engineering / Electronics & Communication Technology'),
 ('EEE','Electrical & Electronics Engineering'),
 ('CSE','Computer Science & Engineering / Information Technology'),
 ('AIML','Artificial Intelligence & Machine Learning / CSE (AI) / CSE (Data Science)'),
 ('BSH','Basic Sciences & Humanities'),
 ('MBA','Master of Business Administration');

INSERT INTO cadres (code, name) VALUES
 ('LECTURER','Lecturer'), ('ASST_PROF','Assistant Professor'),
 ('SR_ASST_PROF','Senior Assistant Professor'), ('ASSOC_PROF','Associate Professor'),
 ('PROFESSOR','Professor');

-- Academic year name is a placeholder default; admin manages years.
INSERT INTO academic_years (name, start_date, end_date) VALUES ('2026-27','2026-06-01','2027-05-31');

INSERT INTO scoring_policies (academic_year_id, cadre_id, version)
SELECT ay.id, c.id, 1 FROM academic_years ay CROSS JOIN cadres c WHERE ay.name = '2026-27';

-- Cadre-wise maximum marks (each cadre totals 100).
INSERT INTO scoring_policy_criteria (policy_id, criterion, max_marks)
SELECT p.id, m.criterion, m.marks
FROM scoring_policies p
JOIN cadres c ON c.id = p.cadre_id
JOIN (
  SELECT 'LECTURER' cadre,'TEACHING_LEARNING' criterion,40 marks UNION ALL
  SELECT 'LECTURER','STUDENT_MENTORING',15 UNION ALL SELECT 'LECTURER','FDP_CERTIFICATIONS',15 UNION ALL
  SELECT 'LECTURER','ADMINISTRATIVE',15 UNION ALL SELECT 'LECTURER','RESEARCH_PUBLICATIONS',5 UNION ALL
  SELECT 'LECTURER','FUNDED_PROJECTS',0 UNION ALL SELECT 'LECTURER','PATENTS_BOOKS_IPR',0 UNION ALL
  SELECT 'LECTURER','OUTREACH',5 UNION ALL SELECT 'LECTURER','MEMBERSHIPS_AWARDS',5 UNION ALL

  SELECT 'ASST_PROF','TEACHING_LEARNING',30 UNION ALL
  SELECT 'ASST_PROF','STUDENT_MENTORING',12 UNION ALL SELECT 'ASST_PROF','FDP_CERTIFICATIONS',10 UNION ALL
  SELECT 'ASST_PROF','ADMINISTRATIVE',15 UNION ALL SELECT 'ASST_PROF','RESEARCH_PUBLICATIONS',15 UNION ALL
  SELECT 'ASST_PROF','FUNDED_PROJECTS',5 UNION ALL SELECT 'ASST_PROF','PATENTS_BOOKS_IPR',3 UNION ALL
  SELECT 'ASST_PROF','OUTREACH',5 UNION ALL SELECT 'ASST_PROF','MEMBERSHIPS_AWARDS',5 UNION ALL

  SELECT 'SR_ASST_PROF','TEACHING_LEARNING',25 UNION ALL
  SELECT 'SR_ASST_PROF','STUDENT_MENTORING',10 UNION ALL SELECT 'SR_ASST_PROF','FDP_CERTIFICATIONS',8 UNION ALL
  SELECT 'SR_ASST_PROF','ADMINISTRATIVE',15 UNION ALL SELECT 'SR_ASST_PROF','RESEARCH_PUBLICATIONS',20 UNION ALL
  SELECT 'SR_ASST_PROF','FUNDED_PROJECTS',7 UNION ALL SELECT 'SR_ASST_PROF','PATENTS_BOOKS_IPR',5 UNION ALL
  SELECT 'SR_ASST_PROF','OUTREACH',5 UNION ALL SELECT 'SR_ASST_PROF','MEMBERSHIPS_AWARDS',5 UNION ALL

  SELECT 'ASSOC_PROF','TEACHING_LEARNING',20 UNION ALL
  SELECT 'ASSOC_PROF','STUDENT_MENTORING',8 UNION ALL SELECT 'ASSOC_PROF','FDP_CERTIFICATIONS',5 UNION ALL
  SELECT 'ASSOC_PROF','ADMINISTRATIVE',15 UNION ALL SELECT 'ASSOC_PROF','RESEARCH_PUBLICATIONS',25 UNION ALL
  SELECT 'ASSOC_PROF','FUNDED_PROJECTS',10 UNION ALL SELECT 'ASSOC_PROF','PATENTS_BOOKS_IPR',7 UNION ALL
  SELECT 'ASSOC_PROF','OUTREACH',5 UNION ALL SELECT 'ASSOC_PROF','MEMBERSHIPS_AWARDS',5 UNION ALL

  SELECT 'PROFESSOR','TEACHING_LEARNING',15 UNION ALL
  SELECT 'PROFESSOR','STUDENT_MENTORING',5 UNION ALL SELECT 'PROFESSOR','FDP_CERTIFICATIONS',5 UNION ALL
  SELECT 'PROFESSOR','ADMINISTRATIVE',20 UNION ALL SELECT 'PROFESSOR','RESEARCH_PUBLICATIONS',25 UNION ALL
  SELECT 'PROFESSOR','FUNDED_PROJECTS',12 UNION ALL SELECT 'PROFESSOR','PATENTS_BOOKS_IPR',8 UNION ALL
  SELECT 'PROFESSOR','OUTREACH',5 UNION ALL SELECT 'PROFESSOR','MEMBERSHIPS_AWARDS',5
) m ON m.cadre = c.code;
